const fs = require('fs');
const lines = fs.readFileSync('src/components/common/sidebar.jsx', 'utf8').split('\n');
const newLines = lines.slice(0, 370);
newLines.push('');
newLines.push('function iconLiveKiosk() {');
newLines.push('  return (');
newLines.push('    <svg viewBox="0 0 24 24" fill="none" className="w-full h-full">');
newLines.push('      <rect x="2" y="3" width="20" height="14" rx="2" stroke="currentColor" strokeWidth="1.6" />');
newLines.push('      <path d="M8 21h8M12 17v4" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round" />');
newLines.push('      <circle cx="12" cy="10" r="3" stroke="currentColor" strokeWidth="1.6" />');
newLines.push('    </svg>');
newLines.push('  );');
newLines.push('}');
newLines.push('');
fs.writeFileSync('src/components/common/sidebar.jsx', newLines.join('\n'));
